import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {mountNovaChat,mountLearningInsight} from '../dist/nova-dialogs.js';
import {learningEvidence} from '../dist/insights-evidence.js';
import {fresh} from '../dist/engine.js';
import {recordNode} from '../dist/constellation.js';
import {safetyReply,safeOutput,reportShape} from '../supabase/functions/nova/policy.js';
const now=Date.now(),state=fresh();state.name='Private child name';state.nova.interests=['private preference'];
for(let i=0;i<12;i++)recordNode(state,{node:'count5',ok:i!==0,hint:i===1,ms:2000,form:['visual','story','symbolic'][i%3],sessionId:'test',now:now-20000+i*1000});
const evidence=learningEvidence(state,now),skill=evidence.skills[0];
assert.equal(evidence.totalFirstAttempts,12);assert.equal(skill.independentCorrect,10);assert.equal(skill.firstAttemptMistakes,1);assert.equal(skill.hintAssisted,1);assert.deepEqual(evidence.completedLevels,[1]);assert.deepEqual(evidence.rememberedNow,[]);assert(!JSON.stringify(evidence).includes('Private'));assert(!JSON.stringify(evidence).includes('private preference'));assert.equal(learningEvidence().totalFirstAttempts,0);
assert.match(safetyReply('Will you be my friend?'),/AI learning buddy/);assert.match(safetyReply('I want to hurt myself'),/trusted grown-up/);assert.match(safetyReply('my password is hello'),/private/);assert.equal(safetyReply('Why is the sky blue?'),null);assert(!safeOutput(''));assert(!safeOutput('I love you'));assert(!safeOutput('See https://example.com'));assert(safeOutput('Hello! Let’s count three stars.'));assert.throws(()=>reportShape({overview:1}));
const win=new Window({url:'http://localhost:5173'}),modal=win.document.createElement('dialog');win.document.body.append(modal);
const tick=()=>new Promise(r=>setTimeout(r,0));
const send=text=>{modal.querySelector('input').value=text;modal.querySelector('form').dispatchEvent(new win.Event('submit',{cancelable:true}));};
const calls=[];let finish,signal;
mountNovaChat(modal,{avatar:'',request:async(kind,messages,s)=>{calls.push(structuredClone(messages));signal=s;return await new Promise(r=>{finish=r;});}});
send('hello');assert(modal.querySelector('[type=submit]').disabled);assert.equal(calls.length,1);modal.querySelector('#nova-close').click();assert(signal.aborted);assert.equal(modal.innerHTML,'');finish({reply:'Late response'});await tick();assert.equal(modal.innerHTML,'');
mountNovaChat(modal,{avatar:'',request:async(kind,messages)=>{calls.push(structuredClone(messages));return {reply:'<img src=x onerror=alert(1)> Hello!'};}});
send('fresh hello');await tick();assert.equal(calls.at(-1).length,1);assert(!modal.querySelector('img'));assert.match(modal.textContent,/<img src=x/);assert(!win.localStorage.length);modal.close();await tick();assert.equal(modal.innerHTML,'');
let tries=0;
mountNovaChat(modal,{avatar:'',request:async()=>{if(!tries++)throw Error('Please try again.');return {reply:'A little joke!'};}});
send('joke');await tick();assert.equal(modal.querySelector('input').value,'joke');assert(!modal.querySelector('input').disabled);send('joke');await tick();assert.match(modal.textContent,/A little joke/);modal.querySelector('#nova-close').click();
const report={overview:'Based on practice.',strengths:['Count to 5'],practice:['One first-attempt mistake.'],nextSteps:['Count objects.','Try pictures.'],forChild:'Thanks for practicing!'};
assert.throws(()=>reportShape({...report,strengths:['High accuracy (10/10)']},evidence),/Unverified/);assert(reportShape({...report,strengths:['10 of 12 independently correct']},evidence));
let reportCalls=0;
mountLearningInsight(modal,{name:'<script>Kid</script>',request:async()=>{if(!reportCalls++)throw Error('Offline');return {report,evidence};}});await tick();assert(!modal.querySelector('#insight-retry').hidden);modal.querySelector('#insight-retry').click();await tick();assert.match(modal.textContent,/12 first attempts/);assert.match(modal.textContent,/One first-attempt mistake/);assert(!modal.querySelector('script'));modal.querySelector('#insight-close').click();assert.equal(modal.innerHTML,'');
await win.happyDOM.abort();
console.log('Passed: factual evidence and privacy, child-friendly guards, temporary chat, abort on close, fresh reopen, safe text rendering, failed chat retry, report retry and actual evidence counts.');
